name: Clojure CI

image: 'docker://openjdk-11-tools-deps'

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: clj -A:test && clj -A:cljs-test
